### ISSUE TITLE
希望配置文件可配置db读写分离

### ISSUE THREAD

**Issue by swtseaman** [nutzam/nutzboot#112]

**Comment by wendal** [comment]
NutDao的读写分离?? 还是说多个数据源??

**Comment by swtseaman** [comment]
NutDao的读写分离，可配置
比如：
jdbc.url=*****
jdbc.slaveUrl=*****

**Comment by wendal** [comment]
嗯，明天吧

**Comment by wendal** [comment]
done by https://github.com/nutzam/nutzboot/pull/114
