### ISSUE TITLE
希望有freemarker的starter...

### ISSUE THREAD

**Issue by EggsBlue** [nutzam/nutzboot#115]
希望nb能有freemarker的starter呀,毕竟一直在用freemarker...

**Comment by wendal** [comment]
把views插件里面的FreeMarkerViewMaker改造一下即可

**Comment by zozoh** [comment]
自动动手，丰衣足食 @TopCoderMyDream

**Comment by EggsBlue** [comment]
那我又要研究研究freemarker的了
![image](https://user-images.githubusercontent.com/20737062/35619683-b5e827fe-06b9-11e8-933e-03d65add70d3.png)

**Comment by wendal** [comment]
很好很强大

**Comment by wendal** [comment]
done by 蛋蛋
