### ISSUE TITLE
freemarker取值的问题

### ISSUE THREAD

**Issue by EggsBlue** [nutzam/nutzboot#120]
页面用freemarker取值,${obj.xxx} 首先从request范围找,然后再从session范围找? 现在的是${obj.xxx}只能是从request,如果想从session拿,必须按照freemarker语法${Session.xxx},是不是应该改成前者? 然后请问一下nb项目中的${base}可能会是什么(难道只有空?)

**Comment by wendal** [comment]
obj只从request取，所有视图都是这个规则吧

至于base为空字符串，是因为默认的context path就是空字符串，jetty/tomcat/undertow均如此，一般也不会改

**Comment by EggsBlue** [comment]
为何我以前用的freemarker从session取值直接${xxx}就能取,现在要${Session.xxx},是我哪里没写好嘛....

**Comment by EggsBlue** [comment]
难道是我们公司专门搞成这样子的?(⊙o⊙)…

**Comment by wendal** [comment]
额，可能你们公司改造吧

**Comment by EggsBlue** [comment]
大叔觉得从session取值直接${xxx},这样如何呢还是按照freemarker标准来比较好呢

**Comment by wendal** [comment]
额，不晓得。。。

**Comment by wendal** [comment]
待议吧。。。

**Comment by EggsBlue** [comment]
好吧O(∩_∩)O~~
