### ISSUE TITLE
undertow.staticPath未配置则启动报错

### ISSUE THREAD

**Issue by tasdingoo** [nutzam/nutzboot#122]
UndertowStarter.java

if (Strings.isBlank(conf.get(PROP_STATIC_PATH)) &&
	     ("static".equals(conf.get(PROP_STATIC_PATH)) || "static/".equals(conf.get(PROP_STATIC_PATH))))
	return Arrays.asList("static", "webapp");
 return Arrays.asList(conf.get(PROP_STATIC_PATH), "static", "webapp");

这一段，如果undertow.staticPath没有配置，则执行return Arrays.asList(conf.get(PROP_STATIC_PATH), "static", "webapp");
但这时候conf.get(PROP_STATIC_PATH)为null，报错

**Comment by wendal** [comment]
嗯嗯,我的锅

**Comment by wendal** [comment]
已经fix过
