### ISSUE TITLE
Swagger的两个问题

### ISSUE THREAD

**Issue by albinhdk** [nutzam/nutzboot#123]
1、如果使用了JDK9，会报javax.xml.bind.annotation.XmlElement这个类找不到，我还不知道原因，事实上这个类在9里面也是有的，不过报错是确实发生了。
![image](https://user-images.githubusercontent.com/1704775/36627046-f223e0de-1977-11e8-91a6-c8ce607d815f.png)

2、会请求谷歌的开源字体，墙内用户体验不好，可以改进一下。

**Comment by wendal** [comment]
第二个问题已解决
