### ISSUE TITLE
有时启动NB项目，总是报端口被占用

### ISSUE THREAD

**Issue by Wizzercn** [nutzam/nutzboot#135]
server.port=5677
jetty.port=8081

配了jetty.port才能正常启动

**Comment by wendal** [comment]
被dubbo占用了?

**Comment by Wizzercn** [comment]
没有，随便换任意端口都提示被占用

**Comment by wendal** [comment]
不写jetty.port的时候, jetty和dubbo使用server.port, 所以冲突了

**Comment by Wizzercn** [comment]
dubbo端口不配置应该是随机端口才对吧，怎么会也用server.port呢

**Comment by wendal** [comment]
并非如此.
是server.port=0的时候才是随机端口

查找路径:
1. 查找该starter专用的端口设置, 例如jetty.port/tomcat.port
2. 没有starter专用的端口设置, 找server.port
3. server.port 有定义, 0就随机, 非0就直接用
4. server.port没定义, 返回starter专用的端口设置的默认值, 例如8080, 8888

```java
conf.putIfAbsent("dubbo.protocol.port", ""+appContext.getServerPort("dubbo.protocol.port", 8888));
```

以dubbo为例, 效果是:
1. `dubbo.protocol.port`和`server.port`均存在, 使用`dubbo.protocol.port`
2. `dubbo.protocol.port`不存在和`server.port`存在, `server.port=0`就随机, 不等于0就直接用`server.port`
3. `dubbo.protocol.port`和`server.port`均不存在, 使用`jetty.port`的默认值,8888

我觉得应该是加个规则, 如果`dubbo.protocol.port`存在且等于0, 随机端口

**Comment by wendal** [comment]
fix in https://github.com/nutzam/nutzboot/commit/241973a66ad7bdf6f120ffe6832b00c26cd298b2
