### ISSUE TITLE
undertow 可否加上gzip

### ISSUE THREAD

**Issue by tasdingoo** [nutzam/nutzboot#138]
RT，目前看应该是没有使用gzip压缩数据的。
可否添加，或以配置形式提供

**Comment by ywjno** [comment]
用nginx来做的话可行么

**Comment by wendal** [comment]
额, 能提供点代码不?

**Comment by tasdingoo** [comment]
undertow 好像内置了这个功能，我找了个例子，可以参考下

https://stackoverflow.com/questions/28295752/compressing-undertow-server-responses

**Comment by wendal** [comment]
done
