### ISSUE TITLE
nutzboot结合freemaker-starter，template文件在jar包中时，会出现模板not found异常

### ISSUE THREAD

**Issue by qixingbaozhu** [nutzam/nutzboot#139]
查看fm文档，应该是模板加载方式问题
Built-in template loaders
void setDirectoryForTemplateLoading(File dir)<---------------当前starter使用的加载类
void setClassForTemplateLoading(Class cl, String basePackagePath)
void setServletContextForTemplateLoading(Object servletContext, String path)

详细讨论可以查阅
`https://nutz.cn/yvr/t/qcnfndh6tajknqqkgt5c5e186t`

**Comment by wendal** [comment]
fixed in 7045541988687e553a60a6848e0f25667f319a1a
