### ISSUE TITLE
nutzboot-starter-nutz-mvc这个依赖不会传递Nutz-Core吗？

### ISSUE THREAD

**Issue by xinkeng0** [nutzam/nutzboot#140]
```
<dependency>
    <groupId>org.nutz</groupId>
    <artifactId>nutzboot-starter-nutz-mvc</artifactId>
</dependency>
```
如上使用这个Starter，并不会传递Nutz-Core依赖，参照
[nutzboot-starter-nutz-mvc/pom.xml](https://github.com/nutzam/nutzboot/blob/v2.2.0/nutzboot-starter/nutzboot-starter-nutz-mvc/pom.xml)，没有导入相关依赖，this is a feature？

**Comment by xinkeng0** [comment]
好吧。。是我的错。
使用构建器获得pom，添加了仓库地址，获得了正确的jar。
建议：是否文档可以把这些说明白一些呢？

**Comment by xinkeng0** [comment]
__

**Comment by ywjno** [comment]
貌似都是用 https://get.nutz.io 这个来创建项目，所以并没遇到该问题
