### ISSUE TITLE
@PropDo 希望不要限制在starter里

### ISSUE THREAD

**Issue by Wizzercn** [nutzam/nutzboot#147]
如题，其他非starter类里也可能会初始化配置参数

建议和ioc机制或者设置扫描的包名/类名来加载/打印输出.

**Comment by EggsBlue** [comment]
估计wendal不干,他可能会说如果其他需要打印propDoc,那就把其他搞成starter,哈哈

**Comment by wendal** [comment]
还没想好,待我想想...

**Comment by wendal** [comment]
fixed
