### ISSUE TITLE
nutzboot-starter-test-junit4中使用NbJUnit4Runner测试结束时未正常关闭应用

### ISSUE THREAD

**Issue by scchenyong** [nutzam/nutzboot#152]
看run函数中的用法，按理使用execute后应采用_shutdown进行关闭。

**Comment by wendal** [comment]
没有_shutdown方法吧?

**Comment by scchenyong** [comment]
使用的版本为
nutzboot-core:2.2.7 org.nutz.boot.NbApp

**Comment by scchenyong** [comment]
我的场景是在用IocBean的depose定义时，在测试用例中未得到执行

**Comment by wendal** [comment]
哦,明白你的意思了,我改一下
