### ISSUE TITLE
【任务】新增配置与使用细节文档

### ISSUE THREAD

**Issue by howe** [nutzam/nutzboot#17]
例如：
1. nutzboot的打包----优先级中
2. nutzboot在服务器的执行方法----优先级中
3. nutzboot在服务器的怎样查看控制台日志打印----优先级中
4. nutzboot各种starter在配置文件中的配置规范（例：jetty在生产环境的配置、dao使用druid连接池的配置使用、各种NoSQL的配置、各种消息队列的配置、多数据源的配置）----优先级高
5. 怎样编写一个nutzboot的starter----优先级中
6. nutzboot的快速入门（最好能对比springboot）----优先级低

**Comment by pangwu86** [comment]
看来要做的事情还很多呀

**Comment by wendal** [comment]
这两天就是撸文档了

**Comment by wendal** [comment]
嗯, 完全写完还需要点时间的
