### ISSUE TITLE
需求:兼容servlets

### ISSUE THREAD

**Issue by TomYule** [nutzam/nutzboot#219]
需求:支持老项目servlets
像某些大型企业 项目用了十年 没有用任何框架 希望nutzboot能支持整合
兼容servlets 正常运行 同时可以运行nutz
兼容web.xml  
大伙评估一下难度 复杂度 可行性

**Comment by wendal** [comment]
不加starter-nutz-mvc, 应该就可以跑吧

**Comment by TomYule** [comment]
那如果想使用  starter-nutz-mvc 呢

**Comment by wendal** [comment]
并不冲突
