### ISSUE TITLE
里程碑需要规划一下吧

### ISSUE THREAD

**Issue by zozoh** [nutzam/nutzboot#33]
里程碑列表应该至少有2个吧

1. 当前正在工作的里程碑
2. 下一个里程碑

最好规划三个

**Comment by wendal** [comment]
定名字还是定里程碑所做的目标呢？如果只是定名字，那多少个也是形同虚设吧

**Comment by zozoh** [comment]
issue 里的 Milestone 一项要选什么？

**Comment by wendal** [comment]
哦， 新建了一个 2.0-GA

**Comment by zozoh** [comment]
里程碑列表估计会同时有两个，等一个快要发布，准备冻结的时候，后续 issue 加到下一个
到时候再说吧，这个 issue 我关了
