### ISSUE TITLE
Web服务类应共享一个超类

### ISSUE THREAD

**Issue by wendal** [nutzam/nutzboot#36]
获取配置信息等逻辑应该封装到超类

**Comment by zozoh** [comment]
能用静态帮助函数的话，可能会更灵活一点。我都是能不用超类就不用

**Comment by wendal** [comment]
不是为了灵活性,是为了让Tomcat/Jetty/Undertow的行为非常接近

**Comment by qinerg** [comment]
其实我一直有一个疑惑，诸如Tomcat/Jetty/Undertow每一个都含有许多的调优参数，而为保持简单，开放出来的参数仅为很少的子集。大多数使用者都被“代表”了。
如何保持简单，又能使用户在需要时可以更灵活的调节内置参数呢？

**Comment by zozoh** [comment]
为参数设置默认值

**Comment by wendal** [comment]
done
