### ISSUE TITLE
是否应该做一个maven plugin,把打包过程自定义

### ISSUE THREAD

**Issue by wendal** [nutzam/nutzboot#38]
当前依赖shade plugin, 局限性:

* 需要手工为Starter标识文件添加合并指令
* 生成runnable jar几乎不可能

其他方案:
* gradle plugin是不是更实际?

**Comment by zozoh** [comment]
因为 gradle 更熟？

**Comment by wendal** [comment]
是因为gradle大概知道怎么写,但maven plugin 没头绪...

**Comment by zozoh** [comment]
嗯嗯

**Comment by wendal** [comment]
做好了
https://github.com/nutzam/nutzboot-maven-plugin
