### ISSUE TITLE
新增了很多个starter,但demo-maker没有相应地添加配置

### ISSUE THREAD

**Issue by wendal** [nutzam/nutzboot#52]
https://github.com/nutzam/nutzboot/tree/dev/nutzboot-demo/nutzboot-demo-maker

**Comment by wendal** [comment]
主要工作:

* 页面添加tomcat/undertow等可选项
* pom.xml模板添加相关依赖项

**Comment by wendal** [comment]
demo-maker对应这个网站 https://get.nutz.io/

**Comment by pangwu86** [comment]
预感最后是me来做

**Comment by wendal** [comment]
群里有人接单了哦

**Comment by pangwu86** [comment]
那好，观察半月，没人做me再动手

**Comment by wendal** [comment]
done by "瞎折腾"

**Comment by pangwu86** [comment]
原来是加那几个东西呀，good
