### ISSUE TITLE
u家三剑客的ProcDoc未编写

### ISSUE THREAD

**Issue by wendal** [nutzam/nutzboot#58]
ureport/urule/uflo均有几个配置项,需要在starter中添加ProcDoc属性

**Comment by wendal** [comment]
参考其他jetty starter, 把可以配置属性做出一个个静态属性和注解就可以了

配置文档: 
* https://wiki.bsdn.org/pages/viewpage.action?pageId=30441805
* https://wiki.bsdn.org/pages/viewpage.action?pageId=75071533
* https://wiki.bsdn.org/pages/viewpage.action?pageId=76448360

**Comment by wendal** [comment]
@TopCoderMyDream 既然已经会用@ProcDoc,有空把这个issue搞一下?

**Comment by TopCoderMyDream** [comment]
我说我是无意见看到的issues你可能不信。。哈哈😄
好，我学习一下这个三剑客👌

**Comment by TopCoderMyDream** [comment]
好像没啥要补的吧...?

**Comment by wendal** [comment]
看我给出的连接，里面有uflo等项目的配置项，starter里面没有明确使用，但事实上是生效的

**Comment by wendal** [comment]
看懂了吗? 例如
uflo.idBlockSize
 uflo.disableScheduler

**Comment by TopCoderMyDream** [comment]
嗯看懂了 (〃'▽'〃)
