### ISSUE TITLE
tomcat需要支持多层资源加载

### ISSUE THREAD

**Issue by wendal** [nutzam/nutzboot#60]
当前仅实现了从classpath或当前目录的static文件夹读取web文件

**Comment by wendal** [comment]
tomcat的资源管理api好蛋疼

**Comment by wendal** [comment]
首先是WebResouceSet,然后是WebResource接口. 前缀已经接近过半,但后者简直不可理喻

**Comment by zozoh** [comment]
N 年不用 tomcat 的飘过

**Comment by wendal** [comment]
done
