### ISSUE TITLE
demo里面的ui基本上等于没有,可否美化一下

### ISSUE THREAD

**Issue by wendal** [nutzam/nutzboot#61]
稍微好看一点, 填一下相关技术的文档链接

**Comment by wendal** [comment]
难度低,但工作量会有点大, 部分美化或者提出一个通用解决方案也可以哦

**Comment by pangwu86** [comment]
啥意思 ，具体工作是啥

**Comment by wendal** [comment]
你跑一下那些demo就知道有什么ui了,当前

**Comment by ywjno** [comment]
那里面全都是直接输出3个值

**Comment by wendal** [comment]
3个值？？

**Comment by wendal** [comment]
啊啊啊, 是不是应该做一套通用的demo UI,然后复制粘贴/引用jar完事

**Comment by ywjno** [comment]
好主意

**Comment by glodenfish** [comment]
公司是用nutzboot做了一个前后端不分离的系统。nutzboot能不能提供一整套的UI供开发使用？

**Comment by glodenfish** [comment]
jquery插件满天飞，不便于管理又不能像angularjs那样统一使用npm管理，统一使用amd或者cmd标准。

**Comment by wendal** [comment]
@luoxinyong 来 #62 留个名?

是不是想做个nutzboot-admin之类的项目呢 ^_^

**Comment by ywjno** [comment]
ui这东西还是让人自己选择算了

**Comment by glodenfish** [comment]
nutzboot-admin在哪我先看看

**Comment by glodenfish** [comment]
对于不涉及前端的人来说还是很难整的。

**Comment by wendal** [comment]
@luoxinyong 没有, 等人来写呢, 或许就是你哦

**Comment by pangwu86** [comment]
me想写，但是。。。。。。。

**Comment by ywjno** [comment]
别写了，让人套现在有的那些皮吧，还挺多的

**Comment by wendal** [comment]
nutzboot-admin应该是套管理后台, 不是界面库, 当然是希望有人写啊

**Comment by wendal** [comment]
看来还是得我出马了^_^

**Comment by wendal** [comment]
done
