### ISSUE TITLE
Nutzboot可以新增feign的starter吗？

### ISSUE THREAD

**Issue by haoqoo** [nutzam/nutzboot#71]
Nutzboot可以新增feign的starter

**Comment by wendal** [comment]
围观 --> https://github.com/OpenFeign/feign 这个?

**Comment by haoqoo** [comment]
是的

**Comment by wendal** [comment]
你想加就pull request好了...

**Comment by haoqoo** [comment]
OK，先试试。

**Comment by wendal** [comment]
是不是要跟Hystrix结合的?

**Comment by wendal** [comment]
有进展吗? 如果遇到瓶颈,拿出来大家讨论一下哦

**Comment by haoqoo** [comment]
嗯，公司有事，最近会搞一个简单版，大家一起完善吧，有些nutz机制还是不太熟……

**Comment by wendal** [comment]
好的

**Comment by haoqoo** [comment]
晕，没创建add_feign_starter分支

**Comment by haoqoo** [comment]
@wendal 帮助创建个add_feign_starter分支

**Comment by wendal** [comment]
莫激动

**Comment by wendal** [comment]
看上去, feign 也是一种RPC的封装?

**Comment by wendal** [comment]
看来可以试一下nutz 1.r.63.r3的IocEventListener机制了

**Comment by haoqoo** [comment]
哦，好滴

**Comment by wendal** [comment]
我来改一下试试

**Comment by haoqoo** [comment]
IocEventListener 具体做了哪些事情？是对象实例化ioc bean后，都会去做IocEventListener的监听？

**Comment by wendal** [comment]
@haoqoo 当前支持2个事件:

1. 对象创建后,但属性还没注入
2. 属性注入完成,触发create事件之后

**Comment by wendal** [comment]
done by #77
