### ISSUE TITLE
nutzboot-starter-beetl使用css的话应该怎么做

### ISSUE THREAD

**Issue by ywjno** [nutzam/nutzboot#74]
比如我有一个 layout.css 需要使用的话，这个文件应该放在哪个文件夹下，以及在页面中该如何写

也就是说，在页面写 `${base}/assets/css/layout.css`的话，这个路径怎么对应到 `resources` 文件夹下

**Comment by haoqoo** [comment]
新建个static文件夹，放入static里

**Comment by wendal** [comment]
因为默认不带jsp, so,请用模板

**Comment by wendal** [comment]
嚓, 看错了

**Comment by wendal** [comment]
beetl模板里面能写 ${base} 的

**Comment by tiankongkm** [comment]
${base} = req.getContextPath()

**Comment by wendal** [comment]
https://github.com/nutzam/nutzboot/blob/dev/doc/struct.md

**Comment by ywjno** [comment]
嗯，看到了
