### ISSUE TITLE
支持一个配置中心

### ISSUE THREAD

**Issue by wendal** [nutzam/nutzboot#94]
例如 disconf ? apollo ?

**Comment by Kerbores** [comment]
spring-cloud-config-server呗,这个最轻最快跑起来,其他的都大同小异

**Comment by wendal** [comment]
它依赖spring 的特性吧?

**Comment by Kerbores** [comment]
Path | Description
-- | --
/{app}/{profile} | Configuration data for app in Spring profile (comma-separated).
/{app}/{profile}/{label} | Add a git label
/{app}/{profiels}{label}/{path} | An environment-specific plain text config file (at "path")

我觉得应该关注的就是可以从这些path上能取到配置信息,然后怎么用配置去取到bean的生成

**Comment by Kerbores** [comment]
https://github.com/spring-cloud-samples/configserver

**Comment by wendal** [comment]
哦, rest形式的

**Comment by wendal** [comment]
先把apollo支持了,解决从无到有的问题
